[package]
name = "nexus-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nexus-private-file = { path = "../nexus-private-file" }
nexus-protocol = { path = "../nexus-protocol" }
nexus-snapshots = { path = "../nexus-snapshots" }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
hmac = "0.12"
getrandom = "0.4"
ring = "0.17.14"

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_System_IO", "Win32_System_Ioctl"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
