import { execFileSync } from 'node:child_process';
import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Inventory is deliberately conservative (includes build dependencies).
// Export only package metadata and license text, never local registry paths.
const app = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const root = path.resolve(app, '../..');
const output = path.join(app, 'src-tauri/resources/notices');
await mkdir(output, { recursive: true });
const packages = new Map();
for (const manifest of ['Cargo.toml', 'apps/nexus-launcher/src-tauri/Cargo.toml']) {
  const metadata = JSON.parse(execFileSync('cargo', ['metadata', '--locked', '--format-version', '1', '--manifest-path', path.join(root, manifest)], {
    cwd: root, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024,
  }));
  for (const pkg of metadata.packages.filter(p => p.source)) {
    packages.set(`rust-${pkg.name}-${pkg.version}`, { name: pkg.name, version: pkg.version,
      license: pkg.license, source: pkg.source, directory: path.dirname(pkg.manifest_path), licenseFile: pkg.license_file });
  }
}
// pnpm's JSON export is generated by the package script, avoiding cmd.exe
// interpolation and Windows .cmd spawning from Node.
const frontend = JSON.parse(await readFile(path.join(output, 'frontend-input.json'), 'utf8'));
for (const group of Object.values(frontend)) for (const pkg of group) {
  for (let i = 0; i < pkg.paths.length; i++) {
    const version = pkg.versions[i] || pkg.versions[0];
    packages.set(`npm-${pkg.name.replaceAll('/', '-')}-${version}`, {
      name: pkg.name, version, license: pkg.license, source: pkg.homepage, directory: pkg.paths[i],
    });
  }
}
const inventory = [];
for (const [id, pkg] of [...packages].sort(([a], [b]) => a.localeCompare(b))) {
  const texts = [];
  async function collect(directory, prefix = '') {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (entry.isFile() && /^(licen[sc]e|copying|copyright|notice|authors)([._-]|$)/i.test(entry.name)) {
        texts.push({ file: prefix + entry.name, text: await readFile(path.join(directory, entry.name), 'utf8') });
      } else if (entry.isDirectory() && /^(licenses?|legal)$/i.test(entry.name)) {
        await collect(path.join(directory, entry.name), prefix + entry.name + '/');
      }
    }
  }
  await collect(pkg.directory);
  if (pkg.licenseFile && !texts.some(t => t.file === pkg.licenseFile)) {
    texts.push({ file: pkg.licenseFile, text: await readFile(path.resolve(pkg.directory, pkg.licenseFile), 'utf8') });
  }
  if (pkg.name === 'libgit2-sys') await collect(path.join(pkg.directory, 'libgit2'), 'libgit2/');
  const file = `${id.replaceAll('@', '')}.txt`;
  if (texts.length) await writeFile(path.join(output, file), texts.map(t => `--- ${t.file} ---\n${t.text}\n`).join('\n'));
  inventory.push({ name: pkg.name, version: pkg.version, license: pkg.license, source: pkg.source,
    text: texts.length ? file : null, reviewRequired: !texts.length || !pkg.license });
}
await copyFile(path.join(root, 'LICENSE'), path.join(output, 'Nexus-LICENSE.txt'));
await copyFile(path.join(root, 'THIRD_PARTY_NOTICES.md'), path.join(output, 'README.md'));
await writeFile(path.join(output, 'components.json'), JSON.stringify(inventory, null, 2) + '\n');
// Remove the raw input containing absolute package-manager paths before packaging.
const { unlink } = await import('node:fs/promises');
await unlink(path.join(output, 'frontend-input.json'));
console.log(`[notices] ${inventory.length} components; ${inventory.filter(p => p.reviewRequired).length} require manual license review`);
