import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {EventEmitter} from 'node:events';import {randomUUID} from 'node:crypto';
import {checkDesktopProfile,installDesktopStartupAudit,startupEvidenceFile} from '../electron/desktop-startup-audit.mjs';
function fixture(t, clock={value:0}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'nexus-desktop-audit-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const put=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s);};
put('apps/desktop/src/ipc.ts',"'dsh-desktop:boot-failed'");put('packages/client/web/src/boot-client.ts','assertEntriesActive(ctx)');put('packages/client/web/src/boot.ts','await mountClient(ctx, this.container)');put('packages/client/web/src/boot-page.ts','this.root.dataset.dshBoot');
const recipe={source:root,stateFile:path.join(root,'state.json'),operationId:randomUUID()};const app=new EventEmitter(),handlers=new Map();let tick;const ipcMain={handle:(channel,callback)=>handlers.set(channel,callback)};
installDesktopStartupAudit({app,ipcMain,recipe,now:()=>clock.value,setTimer:callback=>{tick=callback;return {};},clearTimer:()=>{}});
let mounted=false;const contents={mainFrame:{},getURL:()=> 'dsh-app://app/',isDestroyed:()=>false,executeJavaScript:async()=>mounted};const event={sender:contents,senderFrame:contents.mainFrame};
return {root,put,app,ipcMain,handlers,event,tick:()=>tick(),mount:()=>{mounted=true;},state:()=>JSON.parse(fs.readFileSync(startupEvidenceFile(recipe),'utf8'))};}
test('Desktop checks the actual desktop manifest afresh without resetting it',t=>{const f=fixture(t);checkDesktopProfile(f.root);f.put('profiles/desktop/package.json','broken');assert.throws(()=>checkDesktopProfile(f.root),/JSON is invalid/);assert.equal(fs.readFileSync(path.join(f.root,'profiles/desktop/package.json'),'utf8'),'broken');f.put('profiles/desktop/package.json',JSON.stringify({dsh:{profile:{bundles:['plugin']}}}));checkDesktopProfile(f.root);});
test('a running Host and loaded page do not pass before the real client mount',async t=>{const f=fixture(t);f.ipcMain.handle('dsh-desktop:boot',async()=>({injections:[]}));await f.handlers.get('dsh-desktop:boot')(f.event);await f.tick();assert.equal(f.state().state,'checking');f.mount();await f.tick();assert.equal(f.state().state,'ready');f.ipcMain.handle('dsh-desktop:boot-failed',()=>{});await f.handlers.get('dsh-desktop:boot-failed')(f.event,'later runtime error');assert.equal(f.state().state,'ready');});
test('validated upstream client failure remains visible and a later mount cannot overwrite it',async t=>{const f=fixture(t);f.ipcMain.handle('dsh-desktop:boot',async()=>({}));f.ipcMain.handle('dsh-desktop:boot-failed',()=>{});await f.handlers.get('dsh-desktop:boot')(f.event);await f.handlers.get('dsh-desktop:boot-failed')(f.event,'plugin import failed ?token=secret');f.mount();await f.tick();assert.equal(f.state().state,'failed');assert.match(f.state().error,/plugin import failed/);assert.doesNotMatch(f.state().error,/secret/);});
test('untrusted frame cannot supply startup evidence',async t=>{const f=fixture(t);f.ipcMain.handle('dsh-desktop:boot-failed',()=>{throw Error('rejected');});await assert.rejects(f.handlers.get('dsh-desktop:boot-failed')({...f.event,senderFrame:{}},'forged'));assert.equal(f.state().state,'checking');});

test('a stalled renderer query still reaches unverified timeout',async t=>{const clock={value:0},f=fixture(t,clock);f.ipcMain.handle('dsh-desktop:boot',()=>({}));await f.handlers.get('dsh-desktop:boot')(f.event);f.event.sender.executeJavaScript=()=>new Promise(()=>{});void f.tick();clock.value=91000;await f.tick();assert.equal(f.state().state,'unverified');});
