// Test entry for the real components; keeps test imports independent of page layout.
export { credentialInvalidationCanSettle } from "../src/harness-session";
export { explainBackendError } from "../src/display-format";
export { isRecoverableNoopError } from "../src/display-format";
export { isLoopbackReadinessTarget } from "../src/harness-config";
export type { HarnessConfigDraft } from "../src/harness-config";
export { harnessDraftFromConfig } from "../src/harness-config";
export type { HarnessCandidate } from "../src/harness-config";
export { harnessCandidates } from "../src/harness-config";
export { harnessConfigPayloadFromDraft } from "../src/harness-config";
export type { RuntimeToolStatus } from "../src/runtime-status";
export type { RuntimeStatusPayload } from "../src/runtime-status";
export type { RuntimeStatusViewState } from "../src/runtime-status";
export type { RuntimeStatusPanelProps } from "../src/runtime-status";
export type { RuntimeStatusTransport } from "../src/runtime-status";
export type { RuntimeStatusController } from "../src/runtime-status";
export { runtimeStatusFromResponse } from "../src/runtime-status";
export { createRuntimeStatusController } from "../src/runtime-status";
export { RuntimeStatusPanel } from "../src/runtime-status";
export { DegradedNotice } from "../src/ui-components";
export { MissingReleaseNotice } from "../src/ui-components";
export { HarnessTerminalButton } from "../src/views/workbench";
export { HarnessArgumentReference } from "../src/views/settings";
export { ReadOnlyRecoveryView } from "../src/views/recovery";
export { RecoveryRecordWizard } from "../src/views/recovery";
export { GuideView } from "../src/views/startup";
export { activeProgramSource } from "../src/views/workbench";
export { MaintenanceView } from "../src/views/maintenance";
export { CanaryPanel } from "../src/views/maintenance";
export { CanaryProgress } from "../src/views/maintenance";
export { CanaryReport } from "../src/views/maintenance";
export { SpaceMaintenancePanel } from "../src/views/maintenance";
export { OverviewView } from "../src/views/workbench";
export { HarnessWebPanel } from "../src/views/workbench";
export { CompatibilitySummary } from "../src/views/startup";
export { CompatibilityDialog } from "../src/views/startup";
export { BasicStartupCheck } from "../src/views/startup";
export { ProfilesView } from "../src/views/profiles";
export { requiresErrorBanner } from "../src/operation-notices";
export { ToastNotice } from "../src/operation-notices";
export { OperationStatusPanel } from "../src/operation-notices";
export { RestoreStatusPanel } from "../src/operation-notices";
export { CheckpointsView } from "../src/views/profiles";
export { SnapshotDetail } from "../src/views/profiles";
export { ArchivePath } from "../src/views/updates";
export { OfflinePackagePanel } from "../src/views/updates";
export { OfflineOperationStatus } from "../src/views/updates";
export { UpdatesView } from "../src/views/updates";
export { ProfilePlugins } from "../src/views/profiles";
export { RecoveryModePanel } from "../src/views/recovery";
export { RequestHistory } from "../src/views/recovery";
export { DiagnosticsView } from "../src/views/recovery";
export { LaunchInputsPanel } from "../src/views/settings";
export { HarnessSourcePanel } from "../src/views/settings";
export { SettingsView } from "../src/views/settings";
export { default as App } from "../src/App";
export * as __testI18n from "../src/i18n";
export { MarketplaceSettings } from '../src/views/market';
export { Modal } from "../src/ui-components";
