import { createHash } from 'node:crypto';
import { cleared } from '../../../../.github/scripts/check-git-redistribution.mjs';
import { stageGitNotices } from './bundled-git.mjs';
import { execFileSync } from 'node:child_process';
import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Inventory is deliberately conservative (includes build dependencies).
// Export only package metadata and license text, never local registry paths.
const app = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const root = path.resolve(app, '../..');
const output = path.join(app, 'desktop/resources/notices');
await mkdir(output, { recursive: true });
const packages = new Map();
for (const manifest of ['Cargo.toml']) {
  const metadata = JSON.parse(execFileSync('cargo', ['metadata', '--locked', '--format-version', '1', '--manifest-path', path.join(root, manifest)], {
    cwd: root, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024,
  }));
  for (const pkg of metadata.packages.filter(p => p.source)) {
    packages.set(`rust-${pkg.name}-${pkg.version}`, { name: pkg.name, version: pkg.version,
      license: pkg.license, source: pkg.source, directory: path.dirname(pkg.manifest_path), licenseFile: pkg.license_file });
  }
}
// pnpm's JSON export is generated by the package script, avoiding cmd.exe
// interpolation and Windows .cmd spawning from Node.
const frontend = JSON.parse(await readFile(path.join(output, 'frontend-input.json'), 'utf8'));
for (const group of Object.values(frontend)) for (const pkg of group) {
  for (let i = 0; i < pkg.paths.length; i++) {
    const version = pkg.versions[i] || pkg.versions[0];
    packages.set(`npm-${pkg.name.replaceAll('/', '-')}-${version}`, {
      name: pkg.name, version, license: pkg.license, source: pkg.homepage, directory: pkg.paths[i],
    });
  }
}
const inventory = [];
for (const [id, pkg] of [...packages].sort(([a], [b]) => a.localeCompare(b))) {
  const texts = [];
  async function collect(directory, prefix = '') {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (entry.isFile() && /^(licen[sc]e|copying|copyright|notice|authors)([._-]|$)/i.test(entry.name)) {
        texts.push({ file: prefix + entry.name, text: await readFile(path.join(directory, entry.name), 'utf8') });
      } else if (entry.isDirectory() && /^(licenses?|legal)$/i.test(entry.name)) {
        await collect(path.join(directory, entry.name), prefix + entry.name + '/');
      }
    }
  }
  await collect(pkg.directory);
  if (pkg.licenseFile && !texts.some(t => t.file === pkg.licenseFile)) {
    texts.push({ file: pkg.licenseFile, text: await readFile(path.resolve(pkg.directory, pkg.licenseFile), 'utf8') });
  }
  if (pkg.name === 'libgit2-sys') await collect(path.join(pkg.directory, 'libgit2'), 'libgit2/');
  if (!texts.length && (pkg.name === 'valuable' && pkg.version === '0.1.1' || pkg.name === 'lazy-val' && pkg.version === '1.0.5')) {
    const supplemental = path.join(root, 'docs/audits/third-party-notices-2026-09-23');
    const files = pkg.name === 'valuable'
      ? [['valuable-0.1.1-LICENSE', 'ed60d479b8fd1f64e9cbc3de449a16a53ac1b3d1b6aeb9bf9d190a8e93061b44']]
      : [['lazy-val-1.0.5-package.json', 'a642078ae0684963e5747e9499487a4c649c150bbddbfdfd8eb357bfcbf9c1c2'], ['SPDX-MIT.txt', 'b05785f9f18e6716bab63424b11454513b9943a222595b70411009202fc592b5']];
    for (const [file, sha256] of files) {
      const bytes = await readFile(path.join(supplemental, file));
      if (createHash('sha256').update(bytes).digest('hex') !== sha256) throw new Error('Supplemental notice checksum mismatch: '+file);
      texts.push({file, text: bytes.toString('utf8')});
    }
    if (pkg.name === 'lazy-val') texts.unshift({file: 'Nexus source explanation', text: 'The original package metadata declares MIT and author Vladimir Krivosheev. No separate copyright notice was found at the exact published commit b69ad4119f1b19bdab13c61ee2fcc88d46b89071. The appended SPDX v3.27.0 MIT text is standard license wording, not an upstream LICENSE file; its copyright placeholders do not assert a year or rights holder. Original source and review details: docs/audits/third-party-notices-2026-09-23/README.md in the Nexus source release.'});
  }
  const file = `${id.replaceAll('@', '')}.txt`;
  if (texts.length) await writeFile(path.join(output, file), texts.map(t => `--- ${t.file} ---\n${t.text}\n`).join('\n'));
  inventory.push({ name: pkg.name, version: pkg.version, license: pkg.license, source: pkg.source,
    text: texts.length ? file : null, reviewRequired: !texts.length || !pkg.license });
}
await copyFile(path.join(root, 'crates/nexus-agent/src/vendor/semver.LICENSE'), path.join(output, 'checker-semver-LICENSE.txt'));
inventory.push({ name: 'checker/node-semver', version: '7.7.4', license: 'ISC', source: 'https://github.com/npm/node-semver', text: 'checker-semver-LICENSE.txt', reviewRequired: false });
const gitRuntime = path.join(app, 'desktop/resources/runtime/git');
const runtimeManifest = JSON.parse(await readFile(path.join(app, 'desktop/resources/runtime/manifest.json'), 'utf8'));
await copyFile(path.join(gitRuntime, 'NEXUS-Git-COPYING.txt'), path.join(output, 'bundled-git-LICENSE.txt'));
inventory.push({ name: 'Git (dugite-native)', version: runtimeManifest.git.version, license: 'GPL-2.0-only',
  source: `https://github.com/desktop/dugite-native/releases/tag/${runtimeManifest.git.release}`,
  text: 'bundled-git-LICENSE.txt', reviewRequired: !cleared(JSON.parse(await readFile(path.join(root, 'docs/audits/git-redistribution-2026-09-23/archive-inventory.json'), 'utf8'))) || runtimeManifest.git.gcmExcluded !== true });
const gitMaterials = path.join(gitRuntime, 'NEXUS-NOTICES');
stageGitNotices(gitMaterials, path.join(output, 'bundled-git-notices'));
const gitNotices = JSON.parse(await readFile(path.join(gitMaterials, 'manifest.json'), 'utf8'));
for (const item of gitNotices.files) inventory.push({
  name: `bundled-git/${item.component}`, version: item.version, source: item.source,
  license: 'See original notice', text: `bundled-git-notices/${item.path}`, reviewRequired: !gitNotices.complete,
});
await copyFile(path.join(root, 'LICENSE'), path.join(output, 'Nexus-LICENSE.txt'));
await copyFile(path.join(root, 'THIRD_PARTY_NOTICES.md'), path.join(output, 'README.md'));
await writeFile(path.join(output, 'components.json'), JSON.stringify(inventory, null, 2) + '\n');
// Remove the raw input containing absolute package-manager paths before packaging.
const { unlink } = await import('node:fs/promises');
// Remove only obsolete, generated component text files in this exact folder.
// Do not recursively delete the resource directory or follow subdirectories.
const currentTexts = new Set(inventory.map(component => component.text).filter(Boolean));
for (const entry of await readdir(output, { withFileTypes: true })) {
  if (entry.isFile() && /^(npm|rust)-[^/\\]+\.txt$/.test(entry.name) && !currentTexts.has(entry.name)) {
    await unlink(path.join(output, entry.name));
  }
}
await unlink(path.join(output, 'frontend-input.json'));
console.log(`[notices] ${inventory.length} components; ${inventory.filter(p => p.reviewRequired).length} require manual license review`);
