[package]
name = "nexus-runtime-supply"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait = "0.1"
base64 = "0.22"
flate2 = "1"
nexus-core = { path = "../nexus-core" }
nexus-protocol = { path = "../nexus-protocol" }
p256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }
pgp = { version = "0.20", default-features = false }
reqwest.workspace = true
semver = "1"
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
tar = "0.4"
tokio = { workspace = true, features = ["fs"] }
url = "2"
zip = { version = "6", default-features = false, features = ["deflate-flate2"] }
windows-sys = { workspace = true, features = ["Win32_System_Diagnostics_ToolHelp"] }

[dev-dependencies]
tempfile = "3"
